In [1]:
import numpy as np
import mylinalg

In [2]:
N = 3
A = np.arange(N*N, dtype=float).reshape((N, N))
print(A)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]


In [3]:
x = np.zeros((N, 1))
x[0] = 1.0
print(x)

[[ 1.]
 [ 0.]
 [ 0.]]


In [4]:
print(A.dot(x))

[[ 0.]
 [ 3.]
 [ 6.]]


In [5]:
x[1] = 10.0
print(x)

[[  1.]
 [ 10.]
 [  0.]]


In [6]:
print(A.dot(x))

[[ 10.]
 [ 43.]
 [ 76.]]


In [7]:
x[2] = 0.1
print(x)

[[  1. ]
 [ 10. ]
 [  0.1]]


In [8]:
print(A.dot(x))

[[ 10.2]
 [ 43.5]
 [ 76.8]]


In [9]:
print(mylinalg.multiply_matvec(A, x))

[ 10.2  43.5  76.8]


In [10]:
print(A.dot(A))

[[  15.   18.   21.]
 [  42.   54.   66.]
 [  69.   90.  111.]]


In [11]:
print(mylinalg.multiply_matmat(A, A))

[[  15.   18.   21.]
 [  42.   54.   66.]
 [  69.   90.  111.]]
